In [1]:
import mysql.connector
from datetime import datetime, timedelta

In [2]:
import pandas as pd

In [3]:
from src.database.db_handler import DatabaseHandler
from src.data_receiver.isw import ISWDataCollector
from src.data_receiver.data import WeatherDataCollector
from src.data_receiver.alerts import AlertsAPIHandler

In [4]:
db = DatabaseHandler(
    host="",
    database="",
    user="",
    password="",
    port=3306
)
    
db.connect()
db.create_tables()

In [5]:
# Adding weather

In [6]:
locations = db.get_locations_from_database() # cached implementation later

/home/ubuntu/jn/src/database/db_handler.py:200: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  locations_df = pd.read_sql(query, self.connection)

In [7]:
locations

{'Kyiv City': '50.4501,30.5234',
 'Kyiv': '50.4501,30.5234',
 'Vinnytsia': '49.2328,28.4815',
 'Lutsk': '50.7472,25.3254',
 'Dnipro': '48.4647,35.0462',
 'Donetsk': '48.0159,37.8028',
 'Zhytomyr': '50.2547,28.6587',
 'Uzhhorod': '48.6208,22.2879',
 'Zaporizhzhia': '47.8388,35.1396',
 'Ivano-Frankivsk': '48.9226,24.7111',
 'Kropyvnytskyi': '48.5079,32.2623',
 'Luhansk': '48.5742,39.3075',
 'Lviv': '49.8397,24.0297',
 'Mykolaiv': '46.975,31.9946',
 'Odesa': '46.4825,30.7233',
 'Poltava': '49.5883,34.5514',
 'Rivne': '50.6199,26.2516',
 'Sumy': '50.9077,34.7981',
 'Ternopil': '49.5535,25.5948',
 'Kharkiv': '49.9935,36.2304',
 'Kherson': '46.6354,32.6169',
 'Khmelnytskyi': '49.4229,26.9871',
 'Cherkasy': '49.4444,32.0598',
 'Chernivtsi': '48.2921,25.9358',
 'Chernihiv': '51.4982,31.2893'}

In [9]:
start_date = datetime.strptime("2024-03-21", '%Y-%m-%d')
end_date = datetime.strptime("2024-03-21", '%Y-%m-%d')

collector = WeatherDataCollector("")
weather_data = collector.collect_and_prepare_data(start_date, end_date, locations)

Processing location: Kyiv City (50.4501,30.5234)
Fetching data for Kyiv City (from 2024-03-21 to 2024-03-21...
Successfully processed hourly data for Kyiv City

Processing location: Kyiv (50.4501,30.5234)
Fetching data for Kyiv (from 2024-03-21 to 2024-03-21...
Successfully processed hourly data for Kyiv

Processing location: Vinnytsia (49.2328,28.4815)
Fetching data for Vinnytsia (from 2024-03-21 to 2024-03-21...
Successfully processed hourly data for Vinnytsia

Processing location: Lutsk (50.7472,25.3254)
Fetching data for Lutsk (from 2024-03-21 to 2024-03-21...
Successfully processed hourly data for Lutsk

Processing location: Dnipro (48.4647,35.0462)
Fetching data for Dnipro (from 2024-03-21 to 2024-03-21...
Successfully processed hourly data for Dnipro

Processing location: Donetsk (48.0159,37.8028)
Fetching data for Donetsk (from 2024-03-21 to 2024-03-21...
Successfully processed hourly data for Donetsk

Processing location: Zhytomyr (50.2547,28.6587)
Fetching data for Zhytomyr (from 2024-03-21 to 2024-03-21...
Successfully processed hourly data for Zhytomyr

Processing location: Uzhhorod (48.6208,22.2879)
Fetching data for Uzhhorod (from 2024-03-21 to 2024-03-21...
Successfully processed hourly data for Uzhhorod

Processing location: Zaporizhzhia (47.8388,35.1396)
Fetching data for Zaporizhzhia (from 2024-03-21 to 2024-03-21...
Successfully processed hourly data for Zaporizhzhia

Processing location: Ivano-Frankivsk (48.9226,24.7111)
Fetching data for Ivano-Frankivsk (from 2024-03-21 to 2024-03-21...
Successfully processed hourly data for Ivano-Frankivsk

Processing location: Kropyvnytskyi (48.5079,32.2623)
Fetching data for Kropyvnytskyi (from 2024-03-21 to 2024-03-21...
Successfully processed hourly data for Kropyvnytskyi

Processing location: Luhansk (48.5742,39.3075)
Fetching data for Luhansk (from 2024-03-21 to 2024-03-21...
Successfully processed hourly data for Luhansk

Processing location: Lviv (49.8397,24.0297)
Fetching data for Lviv (from 2024-03-21 to 2024-03-21...
Successfully processed hourly data for Lviv

Processing location: Mykolaiv (46.975,31.9946)
Fetching data for Mykolaiv (from 2024-03-21 to 2024-03-21...
Successfully processed hourly data for Mykolaiv

Processing location: Odesa (46.4825,30.7233)
Fetching data for Odesa (from 2024-03-21 to 2024-03-21...
Successfully processed hourly data for Odesa

Processing location: Poltava (49.5883,34.5514)
Fetching data for Poltava (from 2024-03-21 to 2024-03-21...
Successfully processed hourly data for Poltava

Processing location: Rivne (50.6199,26.2516)
Fetching data for Rivne (from 2024-03-21 to 2024-03-21...
Successfully processed hourly data for Rivne

Processing location: Sumy (50.9077,34.7981)
Fetching data for Sumy (from 2024-03-21 to 2024-03-21...
Successfully processed hourly data for Sumy

Processing location: Ternopil (49.5535,25.5948)
Fetching data for Ternopil (from 2024-03-21 to 2024-03-21...
Successfully processed hourly data for Ternopil

Processing location: Kharkiv (49.9935,36.2304)
Fetching data for Kharkiv (from 2024-03-21 to 2024-03-21...
Successfully processed hourly data for Kharkiv

Processing location: Kherson (46.6354,32.6169)
Fetching data for Kherson (from 2024-03-21 to 2024-03-21...
Successfully processed hourly data for Kherson

Processing location: Khmelnytskyi (49.4229,26.9871)
Fetching data for Khmelnytskyi (from 2024-03-21 to 2024-03-21...
Successfully processed hourly data for Khmelnytskyi

Processing location: Cherkasy (49.4444,32.0598)
Fetching data for Cherkasy (from 2024-03-21 to 2024-03-21...
Successfully processed hourly data for Cherkasy

Processing location: Chernivtsi (48.2921,25.9358)
Fetching data for Chernivtsi (from 2024-03-21 to 2024-03-21...
Successfully processed hourly data for Chernivtsi

Processing location: Chernihiv (51.4982,31.2893)
Fetching data for Chernihiv (from 2024-03-21 to 2024-03-21...
Successfully processed hourly data for Chernihiv

Collection finished. Prepared 600 unique hourly records for database insertion.

In [10]:
weather_data

,location,date,time,datetime,datetimeEpoch,temp,feelslike,humidity,dew,precip,...,feelslikemax,sunrise,moonphase,sunset,feelslikemin,description,tempmin,precipcover,tempmax,sunsetEpoch
0,Kyiv City,2024-03-21,00:00:00,00:00:00,1710972000,3.9,1.0,93.19,2.9,0.0,...,10.4,05:57:45,0.37,18:13:10,-0.1,Partly cloudy throughout the day with morning ...,2.9,4.17,10.4,1711037590
1,Kyiv City,2024-03-21,01:00:00,01:00:00,1710975600,3.9,1.0,91.87,2.7,0.0,...,10.4,05:57:45,0.37,18:13:10,-0.1,Partly cloudy throughout the day with morning ...,2.9,4.17,10.4,1711037590
2,Kyiv City,2024-03-21,02:00:00,02:00:00,1710979200,4.1,1.2,90.59,2.7,0.0,...,10.4,05:57:45,0.37,18:13:10,-0.1,Partly cloudy throughout the day with morning ...,2.9,4.17,10.4,1711037590
3,Kyiv City,2024-03-21,03:00:00,03:00:00,1710982800,4.1,1.3,90.59,2.7,0.0,...,10.4,05:57:45,0.37,18:13:10,-0.1,Partly cloudy throughout the day with morning ...,2.9,4.17,10.4,1711037590
4,Kyiv City,2024-03-21,04:00:00,04:00:00,1710986400,3.3,0.3,91.18,2.0,0.0,...,10.4,05:57:45,0.37,18:13:10,-0.1,Partly cloudy throughout the day with morning ...,2.9,4.17,10.4,1711037590
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,Chernihiv,2024-03-21,19:00:00,19:00:00,1711040400,5.1,3.4,70.62,0.2,0.0,...,11.2,05:54:30,0.37,18:10:20,-1.6,Becoming cloudy in the afternoon.,1.2,0.00,11.2,1711037420
596,Chernihiv,2024-03-21,20:00:00,20:00:00,1711044000,3.9,3.9,79.01,0.6,0.0,...,11.2,05:54:30,0.37,18:10:20,-1.6,Becoming cloudy in the afternoon.,1.2,0.00,11.2,1711037420
597,Chernihiv,2024-03-21,21:00:00,21:00:00,1711047600,4.4,2.5,75.23,0.4,0.0,...,11.2,05:54:30,0.37,18:10:20,-1.6,Becoming cloudy in the afternoon.,1.2,0.00,11.2,1711037420
598,Chernihiv,2024-03-21,22:00:00,22:00:00,1711051200,1.9,-0.5,87.85,0.1,0.0,...,11.2,05:54:30,0.37,18:10:20,-1.6,Becoming cloudy in the afternoon.,1.2,0.00,11.2,1711037420
599,Chernihiv,2024-03-21,23:00:00,23:00:00,1711054800,1.2,1.2,93.04,0.2,0.0,...,11.2,05:54:30,0.37,18:10:20,-1.6,Becoming cloudy in the afternoon.,1.2,0.00,11.2,1711037420

In [11]:
weather_data.dtypes

location           object
date               object
time               object
datetime           object
datetimeEpoch       int64
temp              float64
feelslike         float64
humidity          float64
dew               float64
precip            float64
precipprob        float64
snow              float64
snowdepth         float64
preciptype         object
windgust          float64
windspeed         float64
winddir           float64
pressure          float64
visibility        float64
cloudcover        float64
solarradiation    float64
solarenergy       float64
uvindex           float64
conditions         object
icon               object
stations           object
source             object
sunriseEpoch        int64
feelslikemax      float64
sunrise            object
moonphase         float64
sunset             object
feelslikemin      float64
description        object
tempmin           float64
precipcover       float64
tempmax           float64
sunsetEpoch         int64
dtype: object

In [12]:
weather_region_mapping = db.fetch_region_mapping()
weather_col_mapping = {
    'region': 'location',
    'date': 'date',
    'time': 'time'
}

db.insert_weather_data(weather_data, weather_region_mapping, weather_col_mapping)

Region mapping fetched successfully (25 regions).
Successfully inserted/handled 600 weather records.

In [13]:
weather_data_inserted = db.get_weather_data()

Executing query to fetch weather data...
Retrieved 600 weather records.
JSON data expanded successfully.

/home/ubuntu/jn/src/database/db_handler.py:325: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(sql_query, self.connection, parse_dates=['date'])

In [14]:
weather_data_inserted.sort_values(by=['region_id', 'time'])

,weather_id,region_id,region_name,date,time,dew,icon,snow,temp,precip,...,visibility,description,precipcover,solarenergy,sunsetEpoch,feelslikemax,feelslikemin,sunriseEpoch,datetimeEpoch,solarradiation
264,1,1,Kyiv City,2024-03-21,00:00:00,2.9,partly-cloudy-night,0.0,3.9,0.0,...,NaN,Partly cloudy throughout the day with morning ...,4.17,0.0,1711037590,10.4,-0.1,1710993465,1710972000,0.0
265,2,1,Kyiv City,2024-03-21,01:00:00,2.7,partly-cloudy-night,0.0,3.9,0.0,...,NaN,Partly cloudy throughout the day with morning ...,4.17,0.0,1711037590,10.4,-0.1,1710993465,1710975600,0.0
266,3,1,Kyiv City,2024-03-21,02:00:00,2.7,cloudy,0.0,4.1,0.0,...,NaN,Partly cloudy throughout the day with morning ...,4.17,0.0,1711037590,10.4,-0.1,1710993465,1710979200,0.0
267,4,1,Kyiv City,2024-03-21,03:00:00,2.7,cloudy,0.0,4.1,0.0,...,NaN,Partly cloudy throughout the day with morning ...,4.17,0.0,1711037590,10.4,-0.1,1710993465,1710982800,0.0
268,5,1,Kyiv City,2024-03-21,04:00:00,2.0,cloudy,0.0,3.3,0.0,...,NaN,Partly cloudy throughout the day with morning ...,4.17,0.0,1711037590,10.4,-0.1,1710993465,1710986400,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43,596,25,Chernihiv,2024-03-21,19:00:00,0.2,partly-cloudy-night,0.0,5.1,0.0,...,NaN,Becoming cloudy in the afternoon.,0.00,0.0,1711037420,11.2,-1.6,1710993270,1711040400,0.2
44,597,25,Chernihiv,2024-03-21,20:00:00,0.6,partly-cloudy-night,0.0,3.9,0.0,...,35.0,Becoming cloudy in the afternoon.,0.00,0.0,1711037420,11.2,-1.6,1710993270,1711044000,0.0
45,598,25,Chernihiv,2024-03-21,21:00:00,0.4,partly-cloudy-night,0.0,4.4,0.0,...,NaN,Becoming cloudy in the afternoon.,0.00,0.0,1711037420,11.2,-1.6,1710993270,1711047600,0.0
46,599,25,Chernihiv,2024-03-21,22:00:00,0.1,partly-cloudy-night,0.0,1.9,0.0,...,NaN,Becoming cloudy in the afternoon.,0.00,0.0,1711037420,11.2,-1.6,1710993270,1711051200,0.0
47,600,25,Chernihiv,2024-03-21,23:00:00,0.2,partly-cloudy-night,0.0,1.2,0.0,...,NaN,Becoming cloudy in the afternoon.,0.00,0.0,1711037420,11.2,-1.6,1710993270,1711054800,0.0

In [15]:
weather_data_inserted.dtypes

weather_id                 int64
region_id                  int64
region_name               object
date              datetime64[ns]
time                      object
dew                      float64
icon                      object
snow                     float64
temp                     float64
precip                   float64
source                    object
sunset                    object
sunrise                   object
tempmax                  float64
tempmin                  float64
uvindex                  float64
winddir                  float64
datetime                  object
humidity                 float64
pressure                 float64
stations                  object
windgust                 float64
feelslike                float64
moonphase                float64
snowdepth                float64
windspeed                float64
cloudcover               float64
conditions                object
precipprob               float64
preciptype                object
visibility               float64
description               object
precipcover              float64
solarenergy              float64
sunsetEpoch                int64
feelslikemax             float64
feelslikemin             float64
sunriseEpoch               int64
datetimeEpoch              int64
solarradiation           float64
dtype: object

In [ ]:
# ALERTS

In [14]:
api_handler = AlertsAPIHandler(api_token="")
api_alerts_df = api_handler.fetch_active_alerts_df()

AlertsClient initialized successfully.
Fetching active alerts from API...
Successfully fetched 19 active alerts.

In [15]:
api_alerts_df

,id,location_title,location_type,started_at,finished_at,updated_at,alert_type,location_uid,location_oblast,location_raion,notes,calculated
0,8757,Луганська область,oblast,2022-04-04 19:45:39+03:00,None,2023-10-29 20:22:37.357000+02:00,air_raid,16,Луганська область,None,None,None
1,28288,Автономна Республіка Крим,oblast,2022-12-11 00:22:00+02:00,None,2023-10-29 18:56:12.340000+02:00,air_raid,29,Автономна Республіка Крим,None,Згідно інформації з Офіційних карт тривог,None
2,74845,Липецька територіальна громада,hromada,2024-05-12 11:37:29+03:00,None,2024-05-12 11:37:34.777000+03:00,air_raid,1284,Харківська область,Харківський район,None,None
3,74846,Вовчанська територіальна громада,hromada,2024-05-12 11:37:57+03:00,None,2024-05-12 11:37:58.879000+03:00,air_raid,1313,Харківська область,Чугуївський район,None,None
4,76016,Вовчанська територіальна громада,hromada,2024-05-20 12:31:37+03:00,None,2024-05-20 12:31:39.351000+03:00,artillery_shelling,1313,Харківська область,Чугуївський район,None,None
5,76017,Вовчанська територіальна громада,hromada,2024-05-20 12:31:41+03:00,None,2024-05-20 12:31:44.929000+03:00,urban_fights,1313,Харківська область,Чугуївський район,None,None
6,111012,м. Марганець,city,2025-03-26 11:57:09+02:00,None,2025-03-26 11:57:11.032000+02:00,artillery_shelling,5349,Дніпропетровська область,None,None,None
7,111013,Марганецька територіальна громада,hromada,2025-03-26 11:57:09+02:00,None,2025-03-26 11:57:11.037000+02:00,artillery_shelling,349,Дніпропетровська область,Нікопольський район,None,None
8,111087,Червоногригорівська територіальна громада,hromada,2025-03-26 21:19:38+02:00,None,2025-03-26 21:19:39.259000+02:00,artillery_shelling,356,Дніпропетровська область,Нікопольський район,None,None
9,111170,Покровська територіальна громада,hromada,2025-03-27 14:48:32+02:00,None,2025-03-27 14:48:40.522000+02:00,artillery_shelling,353,Дніпропетровська область,Нікопольський район,None,None
10,111173,Донецька область,oblast,2025-03-27 14:57:58+02:00,None,2025-03-27 14:58:00.413000+02:00,air_raid,28,Донецька область,None,None,None
11,111198,Дніпропетровська область,oblast,2025-03-27 18:08:26+02:00,None,2025-03-27 18:08:29.561000+02:00,air_raid,9,Дніпропетровська область,None,None,None
12,111199,м. Запоріжжя,city,2025-03-27 18:08:28+02:00,None,2025-03-27 18:08:29.757000+02:00,air_raid,5564,Запорізька область,None,None,None
13,111200,Запорізька територіальна громада,hromada,2025-03-27 18:08:28+02:00,None,2025-03-27 18:08:29.773000+02:00,air_raid,564,Запорізька область,Запорізький район,None,None
14,111201,Запорізька область,oblast,2025-03-27 18:08:33+02:00,None,2025-03-27 18:08:36.511000+02:00,air_raid,12,Запорізька область,None,None,None
15,111202,м. Дніпро,city,2025-03-27 18:09:00+02:00,None,2025-03-27 18:09:00.958000+02:00,air_raid,5332,Дніпропетровська область,None,None,None
16,111203,Дніпровська територіальна громада,hromada,2025-03-27 18:09:00+02:00,None,2025-03-27 18:09:00.963000+02:00,air_raid,332,Дніпропетровська область,Дніпровський район,None,None
17,111204,м. Кривий Ріг,city,2025-03-27 18:10:53+02:00,None,2025-03-27 18:10:56.061000+02:00,air_raid,5279,Дніпропетровська область,None,None,None
18,111205,Криворізька територіальна громада,hromada,2025-03-27 18:10:53+02:00,None,2025-03-27 18:10:56.065000+02:00,air_raid,279,Дніпропетровська область,Криворізький район,None,None

In [16]:
api_alerts_df.dtypes

id                                       int64
location_title                          object
location_type                           object
started_at         datetime64[ns, Europe/Kyiv]
finished_at                             object
updated_at         datetime64[ns, Europe/Kyiv]
alert_type                              object
location_uid                            object
location_oblast                         object
location_raion                          object
notes                                   object
calculated                              object
dtype: object

In [17]:
col_mapping = {
    'region': 'location_oblast',
    'start_date': 'started_at',
    'end_date': 'finished_at',
    'type': 'alert_type'
}
region_mapping = {
    'Харківська область': 20,
    'Донецька область': 6,
    'Запорізька область': 9,
    'Дніпропетровська область': 5,
    'Херсонська область': 21,
    'Миколаївська область': 14,
    'Одеська область': 15,
    'Кіровоградська область': 16,
    'Черкаська область': 23,
    'Полтавська область': 16,
    'Сумська область': 18,
    'Київська область': 19,  
    'м. Київ': 1,  
    'Чернігівська область': 25,
    'Житомирська область': 7,
    'Вінницька область': 3,
    'Хмельницька область': 22,
    'Рівненська область': 17,
    'Волинська область': 4, 
    'Тернопільська область': 19,
    'Івано-Франківська область': 10,
    'Чернівецька область': 24,
    'Закарпатська область': 8,  
    'Львівська область': 13,
}

db.insert_alerts_data(api_alerts_df, region_mapping, col_mapping)

Skipping unknown location: Луганська область
Skipping unknown location: Автономна Республіка Крим
Successfully inserted/handled 17 weather records.

In [ ]:
# right now we skip some regions like Луганська область, Автономна Республіка Крим and м. Севастополь

In [19]:
api_alerts_db_df = db.get_alerts()
api_alerts_db_df

Retrieved 17 alert records.

/home/ubuntu/jn/src/database/db_handler.py:512: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(

,alarm_event_id,region_id,region_name,start_datetime_utc,end_datetime_utc,event_type,raw_data
0,17,5,Dnipro,2025-03-27 18:10:53,NaT,air_raid,"{""id"": 111205, ""notes"": null, ""calculated"": nu..."
1,16,5,Dnipro,2025-03-27 18:10:53,NaT,air_raid,"{""id"": 111204, ""notes"": null, ""calculated"": nu..."
2,15,5,Dnipro,2025-03-27 18:09:00,NaT,air_raid,"{""id"": 111203, ""notes"": null, ""calculated"": nu..."
3,14,5,Dnipro,2025-03-27 18:09:00,NaT,air_raid,"{""id"": 111202, ""notes"": null, ""calculated"": nu..."
4,13,9,Zaporizhzhia,2025-03-27 18:08:33,NaT,air_raid,"{""id"": 111201, ""notes"": null, ""calculated"": nu..."
5,12,9,Zaporizhzhia,2025-03-27 18:08:28,NaT,air_raid,"{""id"": 111200, ""notes"": null, ""calculated"": nu..."
6,11,9,Zaporizhzhia,2025-03-27 18:08:28,NaT,air_raid,"{""id"": 111199, ""notes"": null, ""calculated"": nu..."
7,10,5,Dnipro,2025-03-27 18:08:26,NaT,air_raid,"{""id"": 111198, ""notes"": null, ""calculated"": nu..."
8,9,6,Donetsk,2025-03-27 14:57:58,NaT,air_raid,"{""id"": 111173, ""notes"": null, ""calculated"": nu..."
9,8,5,Dnipro,2025-03-27 14:48:32,NaT,artillery_shelling,"{""id"": 111170, ""notes"": null, ""calculated"": nu..."
10,7,5,Dnipro,2025-03-26 21:19:38,NaT,artillery_shelling,"{""id"": 111087, ""notes"": null, ""calculated"": nu..."
11,6,5,Dnipro,2025-03-26 11:57:09,NaT,artillery_shelling,"{""id"": 111013, ""notes"": null, ""calculated"": nu..."
12,5,5,Dnipro,2025-03-26 11:57:09,NaT,artillery_shelling,"{""id"": 111012, ""notes"": null, ""calculated"": nu..."
13,4,20,Kharkiv,2024-05-20 12:31:41,NaT,urban_fights,"{""id"": 76017, ""notes"": null, ""calculated"": nul..."
14,3,20,Kharkiv,2024-05-20 12:31:37,NaT,artillery_shelling,"{""id"": 76016, ""notes"": null, ""calculated"": nul..."
15,2,20,Kharkiv,2024-05-12 11:37:57,NaT,air_raid,"{""id"": 74846, ""notes"": null, ""calculated"": nul..."
16,1,20,Kharkiv,2024-05-12 11:37:29,NaT,air_raid,"{""id"": 74845, ""notes"": null, ""calculated"": nul..."

In [ ]:
# we see a large number of repeated/similar values. 
# at the next stage (analysis, when a file with historical data will be available) 
# we will decide how to work with this data more efficiently

In [20]:
api_alerts_db_df.dtypes

alarm_event_id                 int64
region_id                      int64
region_name                   object
start_datetime_utc    datetime64[ns]
end_datetime_utc      datetime64[ns]
event_type                    object
raw_data                      object
dtype: object

In [ ]:
# REPORTS

In [14]:
isw_collector = ISWDataCollector()
isw_data = isw_collector.collect_data(datetime(2023, 7, 1), datetime(2023, 7, 3))

Successfully collected report for 2023-07-01
Successfully collected report for 2023-07-02
Successfully collected report for 2023-07-03

In [17]:
isw_data

,date,report_text,url
0,2023-07-01,"Russian Offensive Campaign Assessment, July 1,...",https://www.understandingwar.org/backgrounder/...
1,2023-07-02,"Russian Offensive Campaign Assessment, July 2,...",https://www.understandingwar.org/backgrounder/...
2,2023-07-03,"Russian Offensive Campaign Assessment, July 3,...",https://www.understandingwar.org/backgrounder/...

In [20]:
db.insert_isw_report(isw_data)

In [21]:
isw_data_db = db.get_isw_reports()
isw_data_db

/home/ubuntu/jn/src/database/db_handler.py:294: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql(query, self.connection)

,date,content,url
0,2023-07-01,"Russian Offensive Campaign Assessment, July 1,...",https://www.understandingwar.org/backgrounder/...
1,2023-07-02,"Russian Offensive Campaign Assessment, July 2,...",https://www.understandingwar.org/backgrounder/...
2,2023-07-03,"Russian Offensive Campaign Assessment, July 3,...",https://www.understandingwar.org/backgrounder/...

In [ ]:
# FILE INSERTION

In [ ]:
# The insert_weather_data, insert_alerts_data and insert_isw_report methods accept DataFrame as input, 
# adding CSV files is done by simple conversion to DataFrame (pd.read_csv()).

# Through mapping, it is possible to easily link regions and add information to the database, 
# even if the structure of the files is different. For mappings that occur frequently we plan to implement a caching option in the future

# Stub example:

In [21]:
df_from_file = pd.read_csv('alerts_file.csv', encoding="utf-8")
df_from_file

,id2,location_title2,location_type2,started_at2,finished_at2,updated_at2,alert_type2,location_uid2,location_oblast2,location_raion2,notes2,calculated2
0,74845,Липецька територіальна громада,hromada,2024-05-12 11:37:29+03:00,NaN,2024-05-12 11:37:34.777000+03:00,air_raid,1284,обл. Харківська область,Харківський район,NaN,NaN
1,74846,Вовчанська територіальна громада,hromada,2024-05-12 11:37:57+03:00,NaN,2024-05-12 11:37:58.879000+03:00,air_raid,1313,Київська,Чугуївський район,NaN,NaN

In [22]:
col_mapping = {
    'region': 'location_oblast2',
    'start_date': 'started_at2',
    'end_date': 'finished_at2',
    'type': 'alert_type2'
}
region_mapping = {
    'обл. Харківська область': 20,
    'Київська': 2,  
}

db.insert_alerts_data(df_from_file, region_mapping, col_mapping)

Successfully inserted/handled 2 weather records.

In [23]:
df_from_file_db = db.get_alerts()
df_from_file_db

Retrieved 19 alert records.

/home/ubuntu/jn/src/database/db_handler.py:512: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(

,alarm_event_id,region_id,region_name,start_datetime_utc,end_datetime_utc,event_type,raw_data
0,17,5,Dnipro,2025-03-27 18:10:53,NaT,air_raid,"{""id"": 111205, ""notes"": null, ""calculated"": nu..."
1,16,5,Dnipro,2025-03-27 18:10:53,NaT,air_raid,"{""id"": 111204, ""notes"": null, ""calculated"": nu..."
2,14,5,Dnipro,2025-03-27 18:09:00,NaT,air_raid,"{""id"": 111202, ""notes"": null, ""calculated"": nu..."
3,15,5,Dnipro,2025-03-27 18:09:00,NaT,air_raid,"{""id"": 111203, ""notes"": null, ""calculated"": nu..."
4,13,9,Zaporizhzhia,2025-03-27 18:08:33,NaT,air_raid,"{""id"": 111201, ""notes"": null, ""calculated"": nu..."
5,11,9,Zaporizhzhia,2025-03-27 18:08:28,NaT,air_raid,"{""id"": 111199, ""notes"": null, ""calculated"": nu..."
6,12,9,Zaporizhzhia,2025-03-27 18:08:28,NaT,air_raid,"{""id"": 111200, ""notes"": null, ""calculated"": nu..."
7,10,5,Dnipro,2025-03-27 18:08:26,NaT,air_raid,"{""id"": 111198, ""notes"": null, ""calculated"": nu..."
8,9,6,Donetsk,2025-03-27 14:57:58,NaT,air_raid,"{""id"": 111173, ""notes"": null, ""calculated"": nu..."
9,8,5,Dnipro,2025-03-27 14:48:32,NaT,artillery_shelling,"{""id"": 111170, ""notes"": null, ""calculated"": nu..."
10,7,5,Dnipro,2025-03-26 21:19:38,NaT,artillery_shelling,"{""id"": 111087, ""notes"": null, ""calculated"": nu..."
11,5,5,Dnipro,2025-03-26 11:57:09,NaT,artillery_shelling,"{""id"": 111012, ""notes"": null, ""calculated"": nu..."
12,6,5,Dnipro,2025-03-26 11:57:09,NaT,artillery_shelling,"{""id"": 111013, ""notes"": null, ""calculated"": nu..."
13,4,20,Kharkiv,2024-05-20 12:31:41,NaT,urban_fights,"{""id"": 76017, ""notes"": null, ""calculated"": nul..."
14,3,20,Kharkiv,2024-05-20 12:31:37,NaT,artillery_shelling,"{""id"": 76016, ""notes"": null, ""calculated"": nul..."
15,2,20,Kharkiv,2024-05-12 11:37:57,NaT,air_raid,"{""id"": 74846, ""notes"": null, ""calculated"": nul..."
16,1,20,Kharkiv,2024-05-12 11:37:29,NaT,air_raid,"{""id"": 74845, ""notes"": null, ""calculated"": nul..."
17,19,2,Kyiv,2024-05-12 08:37:57,NaT,air_raid,"{""id2"": 74846, ""notes2"": null, ""calculated2"": ..."
18,18,20,Kharkiv,2024-05-12 08:37:29,NaT,air_raid,"{""id2"": 74845, ""notes2"": null, ""calculated2"": ..."

In [ ]:
# Core data is adapted and embedded into the overall structure. 
# Additional data remain untouched, and can be manipulated at the analysis stage using pandas tools

In [ ]:
# iws report from file

In [24]:
isw_data_from_file = pd.read_csv('isw_reports3.csv', encoding="utf-8")
isw_data_from_file

,date,report_text,url
0,2023-03-01,"Kateryna Stepanenko, Karolina Hird, Riley Bail...",https://www.understandingwar.org/backgrounder/...
1,2023-03-02,"Russian Offensive Campaign Assessment, March 2...",https://www.understandingwar.org/backgrounder/...
2,2023-03-03,"Russian Offensive Campaign Assessment, March 3...",https://www.understandingwar.org/backgrounder/...

In [25]:
db.insert_isw_report(isw_data_from_file)

In [26]:
isw_data_db = db.get_isw_reports()
isw_data_db

/home/ubuntu/jn/src/database/db_handler.py:294: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql(query, self.connection)

,date,content,url
0,2023-07-01,"Russian Offensive Campaign Assessment, July 1,...",https://www.understandingwar.org/backgrounder/...
1,2023-07-02,"Russian Offensive Campaign Assessment, July 2,...",https://www.understandingwar.org/backgrounder/...
2,2023-07-03,"Russian Offensive Campaign Assessment, July 3,...",https://www.understandingwar.org/backgrounder/...
3,2023-03-01,"Kateryna Stepanenko, Karolina Hird, Riley Bail...",https://www.understandingwar.org/backgrounder/...
4,2023-03-02,"Russian Offensive Campaign Assessment, March 2...",https://www.understandingwar.org/backgrounder/...
5,2023-03-03,"Russian Offensive Campaign Assessment, March 3...",https://www.understandingwar.org/backgrounder/...